# Generated by Django 4.1.2 on 2023-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AddField(
            model_name="task",
            name="compeleted",
            field=models.BooleanField(default=False),
        ),
    ]
