# Generated by Django 4.1.2 on 2023-03-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_options_task_compeleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="compeleted",
            new_name="completed",
        ),
    ]
